export const myProjects = [
	{
		id: '10',
		title: 'Сайт для изучения английского',
		image: '/images/project-cards/10.png',
		url: 'https://github.com/Suyukee/english-helper',
		tags: ['', 'typescript', 'next-js'],
	},
	{
		id: '9',
		title: 'Сайт рецептов',
		image: '/images/project-cards/9.png',
		url: 'https://github.com/Suyukee/recipes',
		tags: ['', 'typescript', 'next-js', 'react-query'],
	},
	{
		id: '5',
		title: 'Сайт портфолио',
		image: '/images/project-cards/5.png',
		url: 'https://github.com/Suyukee/portfolio',
		tags: ['', 'typescript', 'next-js', 'mui'],
	},
	{
		id: '1',
		title: 'Калькулятор интегрирования',
		image: '/images/project-cards/1.png',
		url: 'https://github.com/Suyukee/define-integral',
		tags: ['', 'typescript', 'next-js'],
	},
	{
		id: '2',
		title: 'Игра на память',
		image: '/images/project-cards/2.png',
		url: 'https://github.com/Suyukee/memory-game',
		tags: ['', 'next-js'],
	},
	{
		id: '6',
		title: 'Dogsterest',
		image: '/images/project-cards/6.png',
		url: 'https://github.com/Suyukee/dogsterest',
		tags: ['', 'next-js'],
	},
	{
		id: '7',
		title: 'Магазин наушников',
		image: '/images/project-cards/7.png',
		url: 'https://github.com/Suyukee/neo-study',
		tags: ['', 'typescript', 'mui'],
	},
	{
		id: '3',
		title: 'Блог',
		image: '/images/project-cards/3.png',
		url: 'https://github.com/Suyukee/blog-on-react',
		tags: ['', 'next-js'],
	},
	{
		id: '4',
		title: 'Отель Solar',
		image: '/images/project-cards/4.png',
		url: 'https://github.com/Suyukee/hotel-solar',
		tags: ['', 'next-js'],
	},
	{
		id: '8',
		title: 'Тестовое для компании',
		image: '/images/project-cards/8.png',
		url: 'https://github.com/Suyukee/copycon-test-task',
		tags: ['', 'typescript', 'rtk-query'],
	},
];
